### ISSUE TITLE
[BUG] Exception: TestCaseResult.__init__() missing 1 required positional argument: 'test_metadata'

### ISSUE THREAD

**Issue by andysmith-sfdc** [tableau/connector-plugin-sdk#1014]
**Describe the bug**
TestCaseResult is instantiated with too few arguments for a disabled smoke test.

Repro: 
- disable the Calcs test, e.g.
      [ConnectionTests]
      StaplesTestEnabled = True
      CastCalcsTestEnabled = False
- run the smoke tests. e.g. python -m tdvt.tdvt run athena --verify
  
Stack:
Exception in thread Thread-10 (do_test_queue_work):
Traceback (most recent call last):
  File "C:\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Python310\lib\site-packages\tdvt\tdvt.py", line 97, in do_test_queue_work
    work.run()
  File "C:\Python310\lib\site-packages\tdvt\tdvt.py", line 208, in run
    failed_tests, skipped_tests, disabled_tests, total_tests = run_tests(self.test_config, self.test_set)
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 731, in run_tests
    all_test_results = run_tests_impl(test_set, tdvt_test_config)
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 704, in run_tests_impl
    do_work(work)
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 314, in do_work
    work.process_test_results(final_test_list)
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 204, in process_test_results
    self.handle_disabled_test_failure(t)
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 153, in handle_disabled_test_failure
    result = self.create_test_result(test_result_file, TestErrorDisabledTest())
  File "C:\Python310\lib\site-packages\tdvt\tdvt_core.py", line 120, in create_test_result
    result = TestResult(test_result_file.test_name, self.test_config, test_result_file.test_file,
  File "C:\Python310\lib\site-packages\tdvt\test_results.py", line 218, in __init__
    self.parse_default_test_cases()
  File "C:\Python310\lib\site-packages\tdvt\test_results.py", line 265, in parse_default_test_cases
    test_result = self.return_testcaseresult_for_not_run_tests(
  File "C:\Python310\lib\site-packages\tdvt\test_results.py", line 227, in return_testcaseresult_for_not_run_tests
    return TestCaseResult('', str(test_case_count), "", test_case_count, '',
TypeError: TestCaseResult.__init__() missing 1 required positional argument: 'test_metadata'

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: Latest

**About you:**
 Name: Andy Smith
 Company: Tableau

**Comment by lukewrites** [comment]
Tracking id: W-12315750
Assigned to @madhurabha
