### ISSUE TITLE
Oauth2 NPE

### ISSUE THREAD

**Issue by jclum** [tableau/connector-plugin-sdk#1107]
Josh Clum

Hello, I'm developing a connector for Tableau that uses oauth2. I'm trying to debug a oauth2 config xml. Everything seems to be going well and I got through most of the issues. The browser opens up, I can log in, and I get redirected. The problem is that I get an NPE in the Tableau code and I'm not sure why. See stack trace at the bottom. Any ideas?

I'm running Tableau 2023.1. 

Here is the trace in the logs:

```
INFO  2023-04-05 12:59:53.658 -0600 grpc-default-executor-0 : com.tableau.oauth.requestors.TokenRequestBuilder - Detected that client secrets expected to be basic encoded in request header.
INFO  2023-04-05 12:59:53.658 -0600 grpc-default-executor-0 : com.tableau.oauth.requestors.BaseOAuthRequestor - Stopping the receiver.
ERROR 2023-04-05 12:59:53.661 -0600 grpc-default-executor-0 : com.tableau.oauth.grpc.OAuthV1GrpcAdapter - Unexpected exception thrown. Throwing exception.
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.1-jre.jar!/:?]
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:125) ~[google-http-client-1.42.0.jar!/:1.42.0]
	at com.google.api.client.http.BasicAuthentication.<init>(BasicAuthentication.java:40) ~[google-http-client-1.42.0.jar!/:1.42.0]
	at com.tableau.oauth.requestors.TokenRequestBuilder.setBasicAuthentication(TokenRequestBuilder.java:72) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.requestors.TokenRequestBuilder.setClientAuthentication(TokenRequestBuilder.java:101) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.requestors.BaseOAuthRequestor.exchangeAuthorizationCodeForTokens(BaseOAuthRequestor.java:509) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.requestors.BaseOAuthRequestor.exchangeAuthorizationCodeForTokens(BaseOAuthRequestor.java:459) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.requestors.BaseOAuthRequestor.getOAuthTokens(BaseOAuthRequestor.java:120) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.service.OAuthService.initialAuthorization(OAuthService.java:116) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.oauth.grpc.OAuthV1GrpcAdapter.initialAuthorization(OAuthV1GrpcAdapter.java:45) ~[oauth-service-impl-2.3.0-jre8.rel.jar!/:?]
	at com.tableau.connect.oauthservice.OAuthServiceGrpc$MethodHandlers.invoke(OAuthServiceGrpc.java:1045) ~[classes!/:?]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:182) ~[grpc-stub-1.49.0.jar!/:1.49.0]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[grpc-api-1.49.0.jar!/:1.49.0]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[grpc-api-1.49.0.jar!/:1.49.0]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[grpc-api-1.49.0.jar!/:1.49.0]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[grpc-api-1.49.0.jar!/:1.49.0]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:354) ~[grpc-core-1.49.0.jar!/:1.49.0]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:866) ~[grpc-core-1.49.0.jar!/:1.49.0]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.49.0.jar!/:1.49.0]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.49.0.jar!/:1.49.0]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by jclum** [comment]
It seems that `clientSecretDesktop` needed to be set.

**Comment by jclum** [comment]
Could the SDK make clientSecretDesktop be optional?

**Comment by rosswbrown** [comment]
Depending on the underlying OAuth provider being used `clientSecretDesktop` can be either required or optional. I've linked a documentation change related to this..
