### ISSUE TITLE
[BUG] Intermittent could not find query task for protocol error

### ISSUE THREAD

**Issue by peeyushgupta1** [tableau/connector-plugin-sdk#1143]
**Describe the bug**
I get the following error intermittently while trying to load a dashboard. I am connecting to Couchbase Analytics using https://exchange.tableau.com/products/627
```
Bad Connection: Tableau could not connect to the data source.
Error Code: FAB9A2C5
Could not find query task for protocol
```
What can be the cause of this error?
In the log files I see the following
```
2023-06-08 21:08:49.427 (,,,,20,112) grpc-default-executor-5 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in fetchResults.
java.lang.Exception: Could not find query task for protocol
	at com.tableau.connect.service.QueryTaskManager.getTask(QueryTaskManager.java:68) ~[jdbcserver.jar:20212.0.14]
	at com.tableau.connect.service.ProtocolService.fetchResults(ProtocolService.java:166) ~[jdbcserver.jar:20212.0.14]
	at com.tableau.connect.grpc.GrpcProtocolService.lambda$fetchResults$4(GrpcProtocolService.java:114) ~[jdbcserver.jar:20212.0.14]
	at com.tableau.connect.grpc.GrpcProtocolService.wrap(GrpcProtocolService.java:292) ~[jdbcserver.jar:20212.0.14]
	at com.tableau.connect.grpc.GrpcProtocolService.fetchResults(GrpcProtocolService.java:113) ~[jdbcserver.jar:20212.0.14]
	at com.tableau.connect.generated.ProtocolServiceGrpc$MethodHandlers.invoke(ProtocolServiceGrpc.java:1504) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[jdbcserver.jar:20212.0.14]
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[jdbcserver.jar:20212.0.14]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Tableau Version: 2021.2

**About you:**
 Name: Peeyush
 Company: Couchbase

**Comment by lukewrites** [comment]
Internal tracking: W-13652655

**Comment by rosswbrown** [comment]
Can you include the details and artifacts mentioned in https://tableau.github.io/connector-plugin-sdk/docs/bug-artifacts. Thanks.

**Comment by rosswbrown** [comment]
We believe this issue has been resolved in newer versions of Tableau. If this is still reproducing with the latest version of Tableau we can re-activate this issue. Thanks.
