### ISSUE TITLE
[BUG] JDBC no longer working with 2019.4 (working fine in 2019.2)

### ISSUE THREAD

**Issue by clach04** [tableau/connector-plugin-sdk#412]
**Describe the bug**

Full details in Tableau case 05555074 (including log files).

JDBC queries are being being sent without a FROM clause in 2019.4, works fine with 2019.2. For a test case see https://github.com/ActianCorp/actian_tableau_connector

**Screenshots**

NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version 2019.4

**About you:**
 Name: Chris Clark
 Company: Actian

**Comment by clach04** [comment]
For those without access to the Tableau case 05555074 details


  * 2019.2 tvdt tests work -nothing of interest in log files
  * 2019..4 - tests fail, even smoke tests.

appears to be sending a SELECT without a FROM clause in the failing case.

extracts from tabquery_logs.zip

    {"ts":"2019-12-16T07:04:32.944","pid":48736,"tid":"d97c","sev":"error","req":"-","sess":"-","site":"-","user":"-","k":"jdbc-error","e":{"excp-code":"9f80fb23","excp-source":"needs-classification","log-code":"0e9a247d","log-source":"indistiguishable"},"v":{"context":"GrpcFetchTask::FetchImpl (D:\\tc\\work\\t194\\g_pc\\modules\\connectors\\tabmixins\\main\\db\\GrpcProtocolProxy.cpp:397)","error-code":"2419","error-messages":["A SELECT statement with an INTO clause after the target list may only be used by host language SQL, or in a stored (database) procedure."],"grpc-status-code":"2","protocol-id":1,"sql-state":"5000A"}}
    {"ts":"2019-12-16T07:04:32.960","pid":48736,"tid":"aed4",



jprotocolserver.log

    2019-12-16 07:04:32.935 -0800 (test-site,,,,1) pool-3-thread-1 : ERROR com.tableausoftware.jdbc.JDBCProtocolImpl - Exception in runQuery for query: SELECT TOP 1 *
    INTO "zTableau_1_43185074_B489_4E0A_97FF_F0FEA60BA08E_1_Connect_CheckSelectIntoCap"
    FROM (SELECT 1 AS COL) AS CHECKTEMP. A SELECT statement with an INTO clause after the target list may only be used by host language SQL, or in a stored (database) procedure.
    2019-12-16 07:04:32.936 -0800 (test-site,,,,1) pool-3-thread-1 : ERROR com.tableau.connect.service.QueryTask - Query for protocol 1 exiting with error class java.sql.SQLException
    2019-12-16 07:04:32.937 -0800 (test-site,,,,1) grpc-default-executor-0 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in fetchResults. SQLState=5000A, ErrorCode=2419.
    java.sql.SQLException: A SELECT statement with an INTO clause after the target list may only be used by host language SQL, or in a stored (database) procedure.
        at com.ingres.gcf.util.SqlExType.getSqlEx(SqlExType.java:127) ~[iijdbc.jar:?]
        at com.ingres.gcf.util.SqlExFactory.get(SqlExFactory.java:96) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.DrvObj.readError(DrvObj.java:856) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.JdbcStmt.readError(JdbcStmt.java:3178) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.DrvObj.readResults(DrvObj.java:640) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.JdbcStmt.readResults(JdbcStmt.java:3075) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.JdbcStmt.readResults(JdbcStmt.java:3026) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.JdbcStmt.exec(JdbcStmt.java:1767) ~[iijdbc.jar:?]
        at com.ingres.gcf.jdbc.JdbcStmt.execute(JdbcStmt.java:726) ~[iijdbc.jar:?]
        at com.tableausoftware.jdbc.JDBCProtocolImpl.runQuery(JDBCProtocolImpl.java:487) ~[jdbcserver.jar:1.5.2]
        at com.tableausoftware.jdbc.JDBCProtocolImpl.runQuery(JDBCProtocolImpl.java:509) ~[jdbcserver.jar:1.5.2]
        at com.tableau.connect.service.QueryTask.readData(QueryTask.java:130) ~[jdbcserver.jar:1.5.2]
        at com.tableau.connect.service.QueryTask.call(QueryTask.java:100) ~[jdbcserver.jar:1.5.2]
        at com.tableau.connect.service.QueryTask.call(QueryTask.java:56) ~[jdbcserver.jar:1.5.2]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_202-ea]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_202-ea]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_202-ea]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_202-ea]

**Comment by clach04** [comment]
Attached log files
[2019.4_jdbc_errors_tabquery_logs.zip](https://github.com/tableau/connector-plugin-sdk/files/3985500/2019.4_jdbc_errors_tabquery_logs.zip)

**Comment by clach04** [comment]
I setup a generic JDBC connection and ran a smoke test and that works. My hunch is that this is specific to SDK based connectors. Our JDBC connector is modeled on the same dialect as the ODBC connector.

**Comment by sidwray** [comment]
Thanks Chris, we'll get this in the backlog to take a closer look!

**Comment by lriggs** [comment]
Could you attach the tdvt logs and results please?

Tableau runs that query when connecting in order to see if the user has permission to create temp tables. It is expected that it might fail in some environments so Tableau should ignore the failure and move on.

You can turn the check off by using CAP_SUPPRESS_TEMP_TABLE_CHECKS=true. Does that help?

**Comment by clach04** [comment]
@lriggs  interesting, blocking temp tables helps in that it does remove the invalid SQL message from the (internal log files) but the actual results appear the same to me. So we may have two different issues at play here.

If you need more information (or want to do a screen share) let me know. I've attached results (with a zip'd up Logs directory) for each run.

 * [temp_blocked.zip](https://github.com/tableau/connector-plugin-sdk/files/3988627/temp_blocked.zip)
 * [temp_allowed.zip](https://github.com/tableau/connector-plugin-sdk/files/3988629/temp_allowed.zip)

**Comment by jainam1995** [comment]
@clach04 Does this error still occur with 2020.2 ?

**Comment by sidwray** [comment]
tfs 1197830

**Comment by rosswbrown** [comment]
Reopen if still occurring.
