### ISSUE TITLE
[BUG] tests generation with TDVT installed as PIP fails

### ISSUE THREAD

**Issue by bpintea** [tableau/connector-plugin-sdk#534]
**Describe the bug**
Packaging TDVT as a Python PIP module, installing it and then attempting to generate the tests for a connector fails; the packaging&installation logs are [attached](https://github.com/tableau/connector-plugin-sdk/files/4779719/packaging.txt), test generation run log inlined below. This has been observed both with the master version, as well as with the `2020.1` tag of TDVT (and with both Python 3.7 and 3.8 and both with or without `wheel` available).

```
PS C:\Users\[...]\Workspace> py -3 -m tdvt.tdvt action --add_ds elastic
Make sure you have already saved the appropriate TDS files in the tds directory.
Adding a new datasource [elastic] ...
Would you like to setup a password file? (y/n) This is suitable for a single connection per tds (standard).y
Enter the datasource password:<REDACTED>
Created file: tds/elastic.password
Enter the logical config to use or type 'list' to see the options or 's' to skip selecting one now:simple_lower
Created ini file: config/elastic.ini
Modifying C:\Users\[...]\Workspace\tds\cast_calcs.elastic.tds
Modifying C:\Users\[...]\Workspace\tds\Staples.elastic.tds
Generating test files from: C:\Program Files\Python37\lib\site-packages\tdvt\logicaltests\generate\input\calcs
Writing test files to: C:\Program Files\Python37\lib\site-packages\tdvt\logicaltests\setup\calcs
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python37\lib\site-packages\tdvt\tdvt.py", line 756, in <module>
    main()
  File "C:\Program Files\Python37\lib\site-packages\tdvt\tdvt.py", line 725, in main
    generate_files(ds_registry, True)
  File "C:\Program Files\Python37\lib\site-packages\tdvt\tdvt_core.py", line 604, in generate_files
    generate_logical_files(logical_input, logical_output, ds_registry, force)
  File "C:\Program Files\Python37\lib\site-packages\tdvt\config_gen\gentests.py", line 292, in generate_logical_files
    process_test_file( os.path.join(input_root, input_filename), output_dir, staples_fields, calcs_fields, ds_registry )
  File "C:\Program Files\Python37\lib\site-packages\tdvt\config_gen\gentests.py", line 127, in process_test_file
    setup_file = open( os.path.join( output_dir, 'setup.' + test_name + '.' + ds + '.xml'), 'w', encoding='utf-8' )
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\Python37\\lib\\site-packages\\tdvt\\logicaltests\\setup\\calcs\\setup.BUGS.B1713.TESTV1.xml'
```

The generation works fine if run from (tdvt) source.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Tableau Version: 2020.2.1
 - SDK version: 2020.1 and master

**Comment by pvanderknyff** [comment]
Hm, it looks like something went wrong when packaging TDVT, the source file for setup.BUGS.B1713 is definitely in the repo. On the TDVT doc page we have instructions for using the "live" version of TDVT, where it uses the exact files in your github repo. Run the following from the top-level tdvt directory:
`py -3 -m pip install -e .`

**Comment by sidwray** [comment]
tfs 1197801
