### ISSUE TITLE
Not seeing proper error messages with the connector

### ISSUE THREAD

**Issue by saikeerthi733** [tableau/connector-plugin-sdk#627]
**About You:**
Name: Venkata Sangaraju
Company: PayPal Inc

**Your question:**
When we are using SDK connector to connect to database, we are not seeing proper error messages that are coming from database. For example connector gives invalid username or password error even though the credentials are correct. Can you please help on how to customize the error messages

**Comment by saugatt** [comment]
Can you tell me what is the error that you are expecting?

**Comment by saikeerthi733** [comment]
When my database password is expired, connector allowed me to connect to database however when i search for a database, it says no databases available. We were expecting error in the first place or show error related to credentials. 
Also, We often get the attached error even though the timeout on server for extracts is 3 hours. We think this error is coming from database but not sure what the actual reason is
[connector_timeout_error.docx](https://github.com/tableau/connector-plugin-sdk/files/5342141/connector_timeout_error.docx)

Your help on this is highly appreciated

**Comment by saikeerthi733** [comment]
seeing this error very often when running extracts 
com.tableausoftware.nativeapi.exceptions.DataSourceException: Deadline Exceeded The table "[schemaname].[tablename]" does not exist. Unable to connect to the Teradata Connector by PayPal server "jackal.vip.paypal.com". Check that the server is running and that you have access privileges to the requested database.

2020-10-08 11:26:01.031 -0700 (Default,,981E8547A4F14D139D618AFE8D650DDD-1:0,1061f861-f62e-4d55-ba3e-ca3bb7502014,1) grpc-default-executor-13 : INFO  com.tableausoftware.jdbc.JDBCProtocolImpl - Closing connection 1.
2020-10-08 11:26:01.050 -0700 (Default,,981E8547A4F14D139D618AFE8D650DDD-1:0,1061f861-f62e-4d55-ba3e-ca3bb7502014,1) grpc-default-executor-11 : ERROR com.tableausoftware.jdbc.JDBCProtocolImpl - Error in readMetadata(null, schemaname,tablename): [Teradata JDBC Driver] [TeraJDBC 16.20.00.13] [Error 751] [SQLState HY000] executeQuery error: The statement has been canceled by another thread
2020-10-08 11:26:01.050 -0700 (Default,,981E8547A4F14D139D618AFE8D650DDD-1:0,1061f861-f62e-4d55-ba3e-ca3bb7502014,1) grpc-default-executor-11 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in readTableMetadata. SQLState=HY000, ErrorCode=751.
java.sql.SQLException: [Teradata JDBC Driver] [TeraJDBC 16.20.00.13] [Error 751] [SQLState HY000] executeQuery error: The statement has been canceled by another thread
        at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:95) ~[?:?]
        at com.teradata.jdbc.jdbc_4.util.ErrorFactory.makeDriverJDBCException(ErrorFactory.java:65) ~[?:?]
        at com.teradata.jdbc.jdbc_4.statemachine.ReceiveInitSubState.action(ReceiveInitSubState.java:91) ~[?:?]
        at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.subStateMachine(StatementReceiveState.java:311) ~[?:?]
        at com.teradata.jdbc.jdbc_4.statemachine.StatementReceiveState.action(StatementReceiveState.java:200) ~[?:?]
        at com.teradata.jdbc.jdbc_4.statemachine.StatementController.runBody(StatementController.java:137) ~[?:?]
        at com.teradata.jdbc.jdbc_4.statemachine.StatementController.run(StatementController.java:128) ~[?:?]
        at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:389) ~[?:?]
        at com.teradata.jdbc.jdbc_4.TDStatement.executeStatement(TDStatement.java:331) ~[?:?]
        at com.teradata.jdbc.jdbc_4.TDStatement.doNonPrepExecuteQuery(TDStatement.java:319) ~[?:?]
        at com.teradata.jdbc.jdbc_4.TDStatement.executeQuery(TDStatement.java:1121) ~[?:?]
        at com.teradata.jdbc.TeraDatabaseMetaData.getColumns(TeraDatabaseMetaData.java:3413) ~[?:?]
        at com.tableausoftware.jdbc.JDBCProtocolImpl.readMetadata(JDBCProtocolImpl.java:785) ~[jdbcserver.jar:3.60.0]
        at com.tableau.connect.service.ProtocolService.readTableMetadata(ProtocolService.java:162) ~[jdbcserver.jar:3.60.0]
        at com.tableau.connect.grpc.GrpcProtocolService.lambda$readTableMetadata$6(GrpcProtocolService.java:125) ~[jdbcserver.jar:3.60.0]
        at com.tableau.connect.grpc.GrpcProtocolService.wrap(GrpcProtocolService.java:249) ~[jdbcserver.jar:3.60.0]
        at com.tableau.connect.grpc.GrpcProtocolService.readTableMetadata(GrpcProtocolService.java:124) ~[jdbcserver.jar:3.60.0]
        at com.tableau.connect.generated.ProtocolServiceGrpc$MethodHandlers.invoke(ProtocolServiceGrpc.java:1487) ~[jdbcserver.jar:3.60.0]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) ~[jdbcserver.jar:3.60.0]
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[jdbcserver.jar:3.60.0]
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[jdbcserver.jar:3.60.0]
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[jdbcserver.jar:3.60.0]
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[jdbcserver.jar:3.60.0]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[jdbcserver.jar:3.60.0]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:818) ~[jdbcserver.jar:3.60.0]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[jdbcserver.jar:3.60.0]

any help on this is highly appreciated

**Comment by saikeerthi733** [comment]
this is resolved. thanks
