### ISSUE TITLE
[BUG] JDBC drivers cannot open up a browser

### ISSUE THREAD

**Issue by nineinchnick** [tableau/connector-plugin-sdk#810]
**Describe the bug**
The Trino JDBC driver supports the OAuth workflow in the same way that Tableau Desktop, that is at some point it can open up a browser where the user can authenticate. This requires passing the `externalAuthentication` JDBC parameter. See [docs](https://trino.io/docs/current/installation/jdbc.html).

When trying to connect using the this driver and the generic JDBC connection option in Tableau, in the `jprotocolserver.log` a following error appears:
```
2021-07-09 15:32:01.142 +0200 (,,,,11,132) grpc-default-executor-12 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in fetchResults. SQLState=null, ErrorCode=0.
java.sql.SQLException: Error executing query
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287) ~[?:?]
	at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240) ~[?:?]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.runQuery(JDBCProtocolImpl.java:603) ~[jdbcserver.jar:20212.0.4]
	at com.tableausoftware.jdbc.JDBCProtocolImpl.runQuery(JDBCProtocolImpl.java:660) ~[jdbcserver.jar:20212.0.4]
	at com.tableau.connect.service.QueryTask.readData(QueryTask.java:134) ~[jdbcserver.jar:20212.0.4]
	at com.tableau.connect.service.QueryTask.call(QueryTask.java:103) ~[jdbcserver.jar:20212.0.4]
	at com.tableau.connect.service.QueryTask.call(QueryTask.java:57) ~[jdbcserver.jar:20212.0.4]
	at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: io.trino.jdbc.$internal.client.auth.external.RedirectException: Desktop Browser is not available. Make sure your Java process is not in headless mode (-Djava.awt.headless=false)
	at io.trino.jdbc.$internal.client.auth.external.DesktopBrowserRedirectHandler.redirectTo(DesktopBrowserRedirectHandler.java:31) ~[?:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at io.trino.jdbc.$internal.client.auth.external.ExternalAuthentication.obtainToken(ExternalAuthentication.java:38) ~[?:?]
	at io.trino.jdbc.$internal.client.auth.external.ExternalAuthenticator.lambda$authenticate$0(ExternalAuthenticator.java:67) ~[?:?]
	at io.trino.jdbc.$internal.client.auth.external.MemoryCachedKnownToken.setupToken(MemoryCachedKnownToken.java:76) ~[?:?]
	at io.trino.jdbc.$internal.client.auth.external.ExternalAuthenticator.authenticate(ExternalAuthenticator.java:61) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.followUpRequest(RetryAndFollowUpInterceptor.java:230) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:119) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
	at io.trino.jdbc.$internal.client.auth.external.ExternalAuthenticator.intercept(ExternalAuthenticator.java:84) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
	at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:68) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
	at io.trino.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
	at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:130) ~[?:?]
	at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:110) ~[?:?]
	at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24) ~[?:?]
	at io.trino.jdbc.QueryExecutor.startQuery(QueryExecutor.java:46) ~[?:?]
	at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:764) ~[?:?]
	at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252) ~[?:?]
	... 10 more
```

The extra properties file used:
```
SSLVerification=FULL
SSL=true
externalAuthentication=true
externalAuthenticationTokenCache=MEMORY
```

When trying the same using a custom connector, that sets the same properties, the only error that gets logged is:
```
2021-07-09 14:44:46.322 +0200 (,,,,5,13) grpc-default-executor-2 : INFO  com.tableau.connect.grpc.GrpcProtocolService - Start local request 13 /enumerateNames.
2021-07-09 14:44:47.776 +0200 (,,,,5,13) grpc-default-executor-2 : ERROR com.tableausoftware.jdbc.JDBCProtocolImpl - Exception in getCatalogs: Authentication failed: 
2021-07-09 14:44:47.777 +0200 (,,,,5,13) grpc-default-executor-2 : INFO  com.tableau.connect.grpc.GrpcProtocolService - End local request 13 /enumerateNames.
```

Although there is a possibility of passing the authentication token to the JDBC driver, adding OAuth support as described in [the SDK docs](https://tableau.github.io/connector-plugin-sdk/docs/oauth) requires specifying the provider parameters, like URLs and client ID and secret, in the connector itself.

Is it somehow possible to disable headless mode for the JVM in which the JDBC driver runs, so it can open up the browser?

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: MacOS
 - Tableau Version: 2021.2

**About you:**
 Name: Jan Waś
 Company: Starburst Data

**Comment by wangxinlei** [comment]
Hi Jan,
So letting the driver handle the pop-up window is not our supported way to do OAuth flow, the supported way is to use the connector SDK OAuth support where you provide the oauthConfig file.
By letting the driver handle the flow it means Tableau Server will not work at all for your connector since the driver installed on is the Tableau Server machine so it cannot prompt the end user a window to sign in. For Tableau Desktop you cannot refresh accessToken if it's expired.
So even though we get you through this problem, you will still have a series of issues along the way.

**Comment by nineinchnick** [comment]
Thanks for the prompt response. Doesn't this make OAuth for Tableau Desktop unusable?

**Comment by nineinchnick** [comment]
Also, [the OAuth docs](https://tableau.github.io/connector-plugin-sdk/docs/oauth) mention that some params in Tableau Server can be configured using `tsm`:
```bash
tsm configuration set -k oauth.config.clients -v "[{\"oauth.config.id\":\"[your_dbclass]\", \"oauth.config.client_id\":\"[your_client_id]\", \"oauth.config.client_secret\":\"[your_client_secret]\", \"oauth.config.redirect_uri\":\"[your_redirect_url]\"}]" --force-keys
```
but [the tsm docs](https://help.tableau.com/current/server-linux/en-us/cli_configuration-set_tsm.htm) don't reference the `oauth` key. Could you confirm that it would be possible to configure all of the settings from `oauthConfig.xml`, or at least `authUri` and `tokenUri`?

**Comment by wangxinlei** [comment]
Hi Jan,
What do you mean by `make OAuth for Tableau Desktop unusable`? OAuth for Tableau Desktop is supported if you define the oauthConfig file correctly.
For the tsm configuration it's supported even though it's not documented in tsm docs. The oauthConfig file will contain authUri and tokenUri but will not contain ClientId/ClientSecret/RedirectUri for server since those are considered as secrets and should not be stored in plain text. Thus those settings are set through tsm config or from site level oauth cient registration, e.g. https://help.tableau.com/current/server/en-us/config_oauth_azure_ad.htm#custom. 
You can see an example oauthConfig content here: https://tableau.github.io/connector-plugin-sdk/docs/oauth

**Comment by nineinchnick** [comment]
The problem is what does it mean "correctly". Our customers can configure Trino/SEP auth to use any OAuth provider. They should not have to ship this configuration to the end-users, especially any secrets. Configuring that in a secured Tableau Server instance is acceptable. Can we set authUri and tokenUri using `tsm configuration` to avoid hardcoding them in `oauthConfig` that ships with our connector?

**Comment by wangxinlei** [comment]
So only set authUri and tokenUri is not enough since for different OAuth Provider(Idp) such as Azure/Gsuite they have different syntax for OAuth flow, such as how to retrieve username, where to set clientId/clientSecret, in body or in header, etc. That's the reason for each different oauth provider we need a separate oauthConfig file, since that file has all the syntax tableau need to know to invoke the oauth flow correctly, and authUri/tokenUri is just one of them.
One thing we are currently working on is supporting multiple-Idps for a single connector, which means you can register as many Idps as you want beforehand and there'll be a dropdown list where you can choose which Idp you wanna use, this will require you to know beforehand what Idps do you wanna support and develop the correct oauthConfig file for them.
Currently we do not support on-the-fly oauthConfig registration, which means all the oauthConfig file must ship with the connector and defined beforehand. We have not heard of a lot requests about this and we currently do not have a feature open for that. 
@sidwray FYI.

**Comment by nineinchnick** [comment]
Going back to the original issue with Tableau Desktop, can you confirm there's currently no way to disable headless mode, like passing `-Djava.awt.headless=false` to the JVM?

**Comment by wangxinlei** [comment]
Yeah you can start tableau like this to append jvm options:
tableau -DJdbcVmOptionsExtras="your options" 
Just to re-iterate we DO NOT recommend this and this will NOT work on Tableau Server.

**Comment by nineinchnick** [comment]
Using `-DJdbcVmOptionsExtras="-Djava.awt.headless=false"` has no effect, headless mode must be enforced in some other way that overrides this. I think I'm done here, that is I don't see any other possible workarounds for this issue, but it's still a valid issue.

**Comment by wangxinlei** [comment]
We have an internal item open for supporting user-defined oauthConfig, I'm tagging this as enhancement.

**Comment by leniartek** [comment]
Hi @wangxinlei is there any timeline we can expect `user-defined oauthConfig` to be delivered in SDK?

**Comment by wangxinlei** [comment]
Hey while we do not have a concrete release target for this feature, we are actively investigating on it. My best guess is it would be in first half of 2022, like 2022.1 or 2022.2.

**Comment by leniartek** [comment]
Thanks for the update @wangxinlei !

**Comment by nineinchnick** [comment]
I found https://help.tableau.com/current/online/en-us/protected_auth.htm#configure-custom-oauth but it seems the allowed values of `Connection Type` are only for build-in connectors, not custom ones.

Also, is #803 a duplicate of this issue?

**Comment by leniartek** [comment]
Hi @wangxinlei any updates on this one?
