### ISSUE TITLE
[BUG] Tableau replaces presto with trino in hostnames

### ISSUE THREAD

**Issue by nineinchnick** [tableau/connector-plugin-sdk#923]
**Describe the bug**
When connecting to Trino or Starburst Enterprise (SEP), using either the Starburst Enterprise or Generic JDBC connector, Tableau always replaces the substring `presto` with `trino`, no matter where it is in the hostname. 

It doesn't matter if the hostname is correct (resolvable) or not.

For example, when using `presto.aws`, it gets replaced with `trino.aws` and the `jprotocolserver.log` file contains the following error, coming from the JDBC driver:
```
2022-02-16 11:14:22.985 +0100 (,,,,12,176) grpc-default-executor-2 : ERROR com.tableau.connect.grpc.GrpcProtocolService - Failed in enumerateNames. SQLState=null, ErrorCode=0.
java.sql.SQLException: Error executing query
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:287) ~[?:?]
        at io.trino.jdbc.TrinoStatement.execute(TrinoStatement.java:240) ~[?:?]
        at io.trino.jdbc.TrinoStatement.executeQuery(TrinoStatement.java:78) ~[?:?]
        at io.trino.jdbc.TrinoDatabaseMetaData.select(TrinoDatabaseMetaData.java:1491) ~[?:?]
        at io.trino.jdbc.TrinoDatabaseMetaData.getTableTypes(TrinoDatabaseMetaData.java:982) ~[?:?]
        at com.tableausoftware.jdbc.JDBCProtocolImpl.getTableTypes(JDBCProtocolImpl.java:777) ~[jdbcserver.jar:20214.0.14]
        at com.tableausoftware.jdbc.JDBCProtocolImpl.enumerateTables(JDBCProtocolImpl.java:765) ~[jdbcserver.jar:20214.0.14]
        at com.tableau.connect.service.ProtocolService.enumerateNames(ProtocolService.java:315) ~[jdbcserver.jar:20214.0.14]
        at com.tableau.connect.grpc.GrpcProtocolService.lambda$enumerateNames$14(GrpcProtocolService.java:217) ~[jdbcserver.jar:20214.0.14]
        at com.tableau.connect.grpc.GrpcProtocolService.wrap(GrpcProtocolService.java:289) ~[jdbcserver.jar:20214.0.14]
        at com.tableau.connect.grpc.GrpcProtocolService.enumerateNames(GrpcProtocolService.java:216) ~[jdbcserver.jar:20214.0.14]
        at com.tableau.connect.generated.ProtocolServiceGrpc$MethodHandlers.invoke(ProtocolServiceGrpc.java:1524) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:180) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[jdbcserver.jar:20214.0.14]
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[jdbcserver.jar:20214.0.14]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.io.UncheckedIOException: java.net.UnknownHostException: trino.aws
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:148) ~[?:?]
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109) ~[?:?]
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24) ~[?:?]
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750) ~[?:?]
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252) ~[?:?]
        ... 23 more
Caused by: java.net.UnknownHostException: trino.aws
        at java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName0(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at java.net.InetAddress.getAllByName(Unknown Source) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.Dns.lambda$static$0(Dns.java:39) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:171) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:135) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.client.auth.external.ExternalAuthenticator.intercept(ExternalAuthenticator.java:84) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$basicAuth$1(OkHttpUtil.java:83) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.client.OkHttpUtil.lambda$userAgent$0(OkHttpUtil.java:69) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[?:?]
        at io.trino.jdbc.$internal.okhttp3.RealCall.execute(RealCall.java:81) ~[?:?]
        at io.trino.jdbc.$internal.client.JsonResponse.execute(JsonResponse.java:130) ~[?:?]
        at io.trino.jdbc.$internal.client.StatementClientV1.<init>(StatementClientV1.java:109) ~[?:?]
        at io.trino.jdbc.$internal.client.StatementClientFactory.newStatementClient(StatementClientFactory.java:24) ~[?:?]
        at io.trino.jdbc.TrinoConnection.startQuery(TrinoConnection.java:750) ~[?:?]
        at io.trino.jdbc.TrinoStatement.internalExecute(TrinoStatement.java:252) ~[?:?]
        ... 23 more
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS, Windows
 - Tableau Version: 2021.4

**About you:**
 Name: Jan Waś
 Company: Starburst Data

**Comment by sidwray** [comment]
I heard the team is looking at this now, and will have an update next week. CC @jie-d

**Comment by jie-d** [comment]
Hi Jan, thanks for reporting this issue! We are planning to fix this in the upcoming April maintenance releases. @nineinchnick
